Repository FrangipaneTeam/terraform-plugin-framework-superschema, pull requests merged in 2023-03, with the labels that each got.

#8 ci: comment issue/pr triage and enable crown
  .github/workflows/issue-triage.yml
  .github/workflows/pr-triage.yml
Labels: CI, size/S

#10 docs: superschema logic and examples
  docs/datasource_example.md
  docs/getting-started.md
  docs/logic.md
  docs/resource_example.md
  docs/why.md
  mkdocs.yml
Labels: size/M, Docs

#14 docs: update readme
  README.md
Labels: size/XS, Docs

#17 feat(template): add code formatting on generated files
  list_attribute.go
  set_attribute.go
  single_nested_attribute.go
  template.go
Labels: CI, size/S, Feature, category/generate, category/template

#16 ci: remove unused
  .github/workflows/issue-triage.yml
  .github/workflows/pr-triage.yml
Labels: CI, size/S
